dataset: mot_crowdhuman

crowdhuman_train_split: train
train_split: train
val_split: val # mot20_train_cross_val_frame_0_5_to_1_0_coco

mot_path_train: data/spine_S1A2
mot_path_val: data/spine_S1A2

resume: models/crowdhuman_deformable_multi_frame/checkpoint_epoch_80.pth

epochs: 50
lr_drop: 10